### ISSUE TITLE
AWS singlenode bootstrap failure

### ISSUE THREAD

**Issue by 0xbboyd** [vrutkovs/my-ocp-40#1]
os version: fedora 31
podman version: 1.9.0
ansible version: 2.9.7
make version: 4.2.1
python version: 3.7.6

environment var overrides:
AWS_BASE_DOMAIN=delta.tolaeon.io
MOUNT_FLAGS=:z
LOG_LEVEL=debug

install-config.aws.yaml.j2:
platform.aws.region = us-east-2

working dir: ./okd-installer
.
├── .aws
│   └── credentials
├── clusters
│   └── dev
│       ├── auth
│       │   ├── kubeadmin-password
│       │   └── kubeconfig
│       ├── install-config.copy.yaml
│       ├── metadata.json
│       ├── .openshift_install.log
│       ├── .openshift_install_state.json
│       ├── terraform.aws.auto.tfvars.json
│       ├── terraform.tfstate
│       ├── terraform.tfvars.json
│       └── tls
│           ├── journal-gatewayd.crt
│           └── journal-gatewayd.key
├── .gitignore
├── install-config.aws.yaml.j2
├── install-config.gcp.yaml.j2
├── install-config.openstack.yaml.j2
├── install-config.ovirt.yaml.j2
├── install-config.vsphere.yaml.j2
├── Makefile
├── manifests
│   └── singlenode
│       ├── cvo-unmanage-quorum-guard.yaml
│       ├── single-ingress.yaml
│       └── single-node-etcd.yaml
├── must-gather.log
├── pull_secret.json
└── ssh-publickey

command: `sudo -E make aws`

Expected: single node OKD 4.4 cluster
Actual: Install error
`time="2020-04-29T19:39:24Z" level=error msg="Attempted to gather debug logs after installation failure: failed to create SSH client: failed to initialize the SSH agent: failed to read directory \"/output/.ssh\": open /output/.ssh: no such file or directory"
time="2020-04-29T19:39:24Z" level=fatal msg="Bootstrap failed to complete: failed to wait for bootstrapping to complete: timed out waiting for the condition"`

Full log attached
[openshift_install.log](https://github.com/vrutkovs/okd-installer/files/4555210/openshift_install.log)

---
working dir: ./okd-installer/clusters/dev
command: `oc adm must-gather | tee ../../must-gather.log`
Full log attached
[must-gather.log](https://github.com/vrutkovs/okd-installer/files/4555221/must-gather.log)

**Comment by vrutkovs** [comment]
Does c53014b27bf88c65f9f557525ffa7c649b402133 fixes it?

Until MCO PR to scale etcd-quorum-guard is not merged use `make aws RELEASE_IMAGE=quay.io/vrutkovs/okd-release:4.4-etcdquorumguard`

**Comment by 0xbboyd** [comment]
I'll try that out and report back. Thanks.

**Comment by 0xbboyd** [comment]
That failed with the same errors, but I was able to successfully run must-gather this time. The file is too big to upload here. Please let me know if there's an address I can send it to somewhere else. Thanks.

**Comment by 0xbboyd** [comment]
You should receive an email at your redhat address with a link to a shared tar.gz archive I've uploaded to google drive.

**Comment by vrutkovs** [comment]
Odd, it says it has installed - `Done applying 0.0.1-2020-05-01-130504` in clusterversion.

Do you still have bootstrap node around? Could you ssh there and fetch the tail (~100 lines) of `bootkube.service` journal?

**Comment by 0xbboyd** [comment]
I destroyed the cluster, but I can duplicate the problem. I'll run it again and see if I can get the journal tail. Thanks.

**Comment by vrutkovs** [comment]
This should now work with `make aws TEMPLATE=install-config.aws-aio.yaml.j2`, latest nighties (and upcoming beta) have patches to support that.

**Comment by 0xbboyd** [comment]
Great thanks. I'll give that a shot.
