### ISSUE TITLE
Format templates using `yq` instead of ansible

### ISSUE THREAD

**Issue by vrutkovs** [vrutkovs/my-ocp-40#2]
`ansible` is an expensive dependency, this repo should be using `yq` instead

**Comment by vrutkovs** [comment]
@elbehery, would you like to pick that up?

**Comment by Elbehery** [comment]
@vrutkovs  sure thing, would you please explain more what is expected ?

**Comment by vrutkovs** [comment]
Sure, in [create-config](https://github.com/vrutkovs/okd-installer/blob/master/Makefile#L69-L73) target selected `TEMPLATE` (`install-config.*.j2`) is being templated into a yaml using ansible.

Templating text files using the whole `ansible` is a bad practice. My idea is:
* Move all templates to `template` folder
* Use `yq` tool to set necessary yaml fields:
```
yq write template/aws.yaml baseDomain "${BASE_DOMAIN}"
```
etc.
* Instead of vendoring `yq` we could use a container: `ghcr.io/linuxserver/yq:version-2.12.0`

**Comment by vrutkovs** [comment]
Fixed in 8e79f90222bfbb4721fe8aa971d1f9671543ce14
